name: essentialsTP
main: essentialsTP\essentialsTP
version: 1.2.2
api: 5.0.0
extensions: [sqlite3]
commands:
 home:
  description: Teleports you home /home will list homes /home <homename> will teleport you.
  usage: "/home or /home <homename>"
  permission: essentialstp.command.home
 sethome:
  description: Sets your home, use names for multiple homes.
  usage: "/sethome <homename>"
  permission: essentialstp.command.sethome
 delhome:
  description: Delete your selected home.
  usage: "/delhome <homename>"
  permission: essentialstp.command.delhome
 back:
  description: Teleports you to your last known death location.
  usage: "/back"
  permission: essentialstp.command.back
 wild:
  description: Teleport to a random location in the world.
  usage: "/wild"
  permission: essentialstp.command.wild
 setspawn:
  description: Sets world spawn point.
  usage: "/setspawn"
  permission: essentialstp.command.setspawn
 spawn:
  description: Teleports to world spawn point.
  usage: "/spawn"
  permission: essentialstp.command.spawn
 warp:
  description: Warps you to a location /warp will list warps /warp <warpname> will teleport you.
  usage: "/warp or /warp <warpname>"
  permission: essentialstp.command.tpahere
 setwarp:
  description: Sets a warp location.
  usage: "/setwarp <warpname>"
  permission: essentialstp.command.setwarp
 delwarp:
  description: Delete a warp location.
  usage: "/delwarp <warpname>"
  permission: essentialstp.command.delwarp
 tpa:
  description: Send teleport request to player to teleport you to player.
  usage: "/tpa <player>"
  permission: essentialstp.command.tpa
 tpahere:
  description: Send teleport request to teleport player to you.
  usage: "/tpahere <player>"
  permission: essentialstp.command.tpahere
 tpaccept:
  description: Accept a teleport request.
  usage: "/tpaccept"
  permission: essentialstp.command.tpaccept
 tpdeny:
   description: decline all active teleport requests.
   usage: "/tpdeny"
   permission: essentialstp.command.tpdeny

